name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version your project uses

      - name: Install dependencies
        run: npm install  # or `yarn install`

      - name: Lint code
        run: npm run lint  # or `yarn lint` if you have linting configured

      - name: Run tests
        run: npm test  # or `yarn test`

      - name: Build application (if needed)
        run: npm run build  # or `yarn build` if your backend needs to be built

      # Optionally add deployment steps here
